CREATE TABLE `plugin` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`dirname` VARCHAR(255) NOT NULL DEFAULT '0' COMMENT '文件名',
	`type` INT(11) NULL DEFAULT '1' COMMENT '类型',
	`name` VARCHAR(50) NOT NULL COMMENT '名称',
	`author` VARCHAR(50) NOT NULL,
	`mail` VARCHAR(50) NULL DEFAULT NULL,
	`enable` TINYINT(1) NULL DEFAULT '0',
	`installed` TINYINT(1) NOT NULL DEFAULT '0',
	`config` JSON NULL DEFAULT NULL,
	PRIMARY KEY (`id`),
	UNIQUE INDEX `dirname` (`dirname`)
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;
